---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3     # 3个副本
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: flask
          image: 88382078/flask:v1.0.0
#          resources:
#            requests:
#              cpu: 3
#              memory: 50M
#            limits:
#              cpu: 5
#              memory: 100M
          env:
            - name: imageVersion
              value: "{v1:no livenessProbe, readinessProbe, lifecycle}"
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080

  selector:
    app: flask

