apiVersion: v1    #用于展示Prometheus的界面
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30091
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus