apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-web
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  type: NodePort
  ports:
  - port: 9090
    name: web
    nodePort: 30090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s