apiVersion: v1
kind: Service
metadata:
  name: flask-service-prometheus
  labels:
    app: flask-pod-svc
spec:
  type: NodePort
  ports:
  - port: 80
    name: service-port
    protocol: TCP
    targetPort: 80

  selector:
    app: flask