apiVersion: v1
kind: Namespace
metadata:
  name: flask-cluster
---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: flask-deployment
        namespace: flask-cluster
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3     # 3个副本
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: 88382078/flask-v1.0:1.0.0
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-cluster
spec:
  type: NodePort
  ports:
  - port: 8080
    name: service-port
    nodePort: 30094
    protocol: TCP
    targetPort: 80

  selector:
    app: flask