apiVersion: v1
kind: Pod
metadata:
        name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64     # 强制要求架构是amd64
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: disk-type
              operator: In
              values:
              - ssd       # 权重1,磁盘是ssd
  containers:
    - name: with-node-affinity
      image: redis