apiVersion: v1
kind: Pod
metadata:
        name: test-taints
spec:
  containers:
    - name: busybox
      image: busybox
  tolerations:
    - key: "key"
      operator: "Exists"
      effect: "NoSchedule"
#  tolerations:
#    - key: "key"
#      operator: "Exists"
#      value: "value"
#      effect: "NoSchedule"
#  nodeSelector: #定向调度到zone是north的node
#    zone: north