apiVersion: v1
kind: Pod
metadata:
        name: pode-flag2
        labels:
          security: "S1"
          app: "redis"
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector: #定向调度到zone是north的node
    zone: east