apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
        name: php-apache
spec:
  scaleTargetRef:          #目标作用对象，可以是Deployment,RC,PeplicaSet
    apiVersion: app/v1
    kind: Deployment
    name: nginx-deployment    # 扩容对象
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50    # 期望每个Pod的CPU使用率都是50%，基于Pod设置的CPU Request值计算，例如值为200m，系统维持Pod实际使用率为100m